version: '3.6'
services:
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - DB_USERNAME=testuser
      - DB_PASSWORD=1234
      - DB_HOST=10.99.80.67
      - DB_PORT=5432
      - DB_NAME=mdl
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"

  #   build: nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - api
