version: '3.6'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  # web:
  #   build: nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - api
