# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class InlineObject5(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    InlineObject5 - a model defined in OpenAPI

        product_id: The product_id of this InlineObject5 [Optional].
    """

    product_id: Optional[int] = None

InlineObject5.update_forward_refs()
