type: object
properties:
  ObjectID:
    type: integer
    example: 1
  ProductName:
    type: string
    example: car
  Price:
    type: integer
    example: 2000
  ImageUrl:
    type: string
    example: /car2.jpg
    