type: object
properties:
  ProductID:
    type: integer
    example: 1
  ProductName:
    type: string
    example: car
  Price:
    type: integer
    example: 2000
  Image:
    type: string
    example: /car2.jpg
  Description:
    type: string
    example: BMW
    