type: array
items: 
  $ref: './product.yaml'

example:
  - ProductID: 3
    ProductName: car1
    Price: 1000
    Image: C:\Users\jusong\Desktop\car.jpg
    Description: this is BMW
  
  - ProductID: 4
    ProductName: car2
    Price: 2000
    Image: this is KIA