# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class InlineObject2(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    InlineObject2 - a model defined in OpenAPI

        user_id: The user_id of this InlineObject2 [Optional].
        password: The password of this InlineObject2 [Optional].
    """

    user_id: Optional[str] = None
    password: Optional[str] = None

InlineObject2.update_forward_refs()
