# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Product(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Product - a model defined in OpenAPI

        object_id: The object_id of this Product [Optional].
        product_name: The product_name of this Product [Optional].
        price: The price of this Product [Optional].
        image_url: The image_url of this Product [Optional].
    """

    object_id: Optional[int] = None
    product_name: Optional[str] = None
    price: Optional[int] = None
    image_url: Optional[str] = None

Product.update_forward_refs()
